In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [18]:
salepred={'Year':[2013,2014,2015,2016,2017,2018],'Sales':[110,100,250,275,230,300]}
sp=pd.DataFrame(salepred)
sp

Year  Sales
0  2013    110
1  2014    100
2  2015    250
3  2016    275
4  2017    230
5  2018    300

In [19]:
test={'Year':[2019,2020,2021]}
test_=pd.DataFrame(test)
test_

Year
0  2019
1  2020
2  2021

In [22]:
Year_=np.array(salepred['Year']).reshape(-1,1)
Year_

array([[2013],
       [2014],
       [2015],
       [2016],
       [2017],
       [2018]])

In [23]:
X=Year_
y=salepred['Sales']

In [24]:
lin_reg=LinearRegression(fit_intercept=True)

In [25]:
lin_reg.fit(X,y)

LinearRegression()

In [26]:
print('Linear Model Coeff m:{}'.format(lin_reg.coef_))
print('Linear Model Intercept c: {}'.format(lin_reg.intercept_))

Linear Model Coeff m:[39.]
Linear Model Intercept c: -78393.6666666667


In [27]:
y_predict=lin_reg.predict(X)

In [28]:
y_predict

array([113.33333333, 152.33333333, 191.33333333, 230.33333333,
       269.33333333, 308.33333333])

In [29]:
y_predict=lin_reg.predict(test_)

In [30]:
y_predict

array([347.33333333, 386.33333333, 425.33333333])